# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import cheese_pb2 as cheese__pb2


class CheeseServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Order = channel.unary_unary(
        '/cheesefarm.CheeseService/Order',
        request_serializer=cheese__pb2.CheeseRequest.SerializeToString,
        response_deserializer=cheese__pb2.Cheese.FromString,
        )


class CheeseServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Order(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CheeseServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Order': grpc.unary_unary_rpc_method_handler(
          servicer.Order,
          request_deserializer=cheese__pb2.CheeseRequest.FromString,
          response_serializer=cheese__pb2.Cheese.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'cheesefarm.CheeseService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
